steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chatgpt-rag', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chatgpt-rag']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud run deploy chatgpt-rag-api \
          --image gcr.io/$PROJECT_ID/chatgpt-rag \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars OPENAI_API_KEY=$OPENAI_API_KEY,PINECONE_API_KEY=$PINECONE_API_KEY,PINECONE_ENVIRONMENT=$PINECONE_ENVIRONMENT,PINECONE_INDEX=$PINECONE_INDEX

availableSecrets:
  secretManager:
    env:
      - versionName: projects/$PROJECT_ID/secrets/openai-api-key/versions/latest
        env: OPENAI_API_KEY
      - versionName: projects/$PROJECT_ID/secrets/pinecone-api-key/versions/latest
        env: PINECONE_API_KEY
      - versionName: projects/$PROJECT_ID/secrets/pinecone-environment/versions/latest
        env: PINECONE_ENVIRONMENT
      - versionName: projects/$PROJECT_ID/secrets/pinecone-index/versions/latest
        env: PINECONE_INDEX

images:
  - 'gcr.io/$PROJECT_ID/chatgpt-rag'
