steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo '🔍 BEGIN app.py content:'
        cat backend/app.py
        echo '🔍 END app.py content'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --no-cache
      - -f
      - backend/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/pinecone-rag-backend
      - backend

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/pinecone-rag-backend

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - pinecone-rag-backend
      - --image
      - gcr.io/$PROJECT_ID/pinecone-rag-backend
      - --platform
      - managed
      - --region
      - us-central1
      - --allow-unauthenticated
      - --set-env-vars
      - |
        OPENAI_API_KEY=sk-xxxxxxx,PINECONE_API_KEY=pcsk-xxxxxxx,PINECONE_INDEX=rag-index,PINECONE_ENVIRONMENT=us-east-1

images:
  - gcr.io/$PROJECT_ID/pinecone-rag-backend

options:
  logging: CLOUD_LOGGING_ONLY
